# Generated by Django 4.2 on 2023-04-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер дома')),
                ('etazhnost', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('ploshad', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('json_dadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='NaseleniPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Населенный пунт',
                'verbose_name_plural': 'Населеные пункты',
            },
        ),
        migrations.CreateModel(
            name='Uliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('naseleni_punkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.naselenipunkt', verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='FotoDoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='', verbose_name='Фото')),
                ('data_foto', models.DateField(blank=True, null=True, verbose_name='Дата фото')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresa.dom')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото дома',
            },
        ),
        migrations.AddField(
            model_name='dom',
            name='uliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.uliza', verbose_name='Улица'),
        ),
    ]
