# Generated by Django 4.2 on 2023-04-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotodoma',
            old_name='data_foto',
            new_name='data',
        ),
        migrations.AddField(
            model_name='dom',
            name='god_realizazii',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год реализации'),
        ),
        migrations.CreateModel(
            name='VideoDoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата видео')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresa.dom')),
            ],
            options={
                'verbose_name': 'Видео дома',
                'verbose_name_plural': 'Видео дома',
            },
        ),
        migrations.CreateModel(
            name='FailDoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail', models.FileField(upload_to='', verbose_name='Файл')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата видео')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresa.dom')),
            ],
            options={
                'verbose_name': 'Файл дома',
                'verbose_name_plural': 'Файлы дома',
            },
        ),
    ]
