# Generated by Django 4.2 on 2023-04-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vladelzi_zdani', '0001_initial'),
        ('adresa', '0002_rename_data_foto_fotodoma_data_dom_god_realizazii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='vladelez_zdania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vladelzi_zdani.vladelezzdania', verbose_name='Владелец здания'),
        ),
    ]
