# Generated by Django 4.2 on 2023-04-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0003_dom_vladelez_zdania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название округа')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
            },
        ),
        migrations.AddField(
            model_name='uliza',
            name='okrug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.okrug', verbose_name='Округ'),
        ),
    ]
