# Generated by Django 4.2 on 2023-04-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0004_okrug_uliza_okrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uliza',
            name='okrug',
        ),
    ]
