# Generated by Django 4.2 on 2023-04-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vladelzi_zdani', '0002_zastroyshik'),
        ('adresa', '0005_remove_uliza_okrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='SostoyanieDoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Состояние дома')),
            ],
            options={
                'verbose_name': 'Состояние дома',
                'verbose_name_plural': 'Состояния дома',
            },
        ),
        migrations.CreateModel(
            name='TipObecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.AddField(
            model_name='dom',
            name='zastroyshik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vladelzi_zdani.zastroyshik', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='dom',
            name='sostoyanie_doma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.sostoyaniedoma', verbose_name='Состояние дома'),
        ),
    ]
