# Generated by Django 4.2 on 2023-04-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0006_rayon_sostoyaniedoma_tipobecta_dom_zastroyshik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='tip_obecta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.tipobecta', verbose_name='Тип объекта'),
        ),
    ]
