# Generated by Django 4.2 on 2023-04-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0007_dom_tip_obecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='naselenipunkt',
            name='okrug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.okrug', verbose_name='Округ'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='naseleni_punkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.naselenipunkt', verbose_name='Район'),
        ),
    ]
