# Generated by Django 4.2 on 2023-04-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0008_naselenipunkt_okrug_rayon_naseleni_punkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uliza',
            name='naseleni_punkt',
        ),
        migrations.AddField(
            model_name='uliza',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresa.rayon', verbose_name='Район'),
        ),
    ]
