# Generated by Django 4.2 on 2023-04-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0011_remove_naselenipunkt_rayon_remove_rayon_okrug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopPoleDoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Доп поле для домов',
                'verbose_name_plural': 'Доп поля для домов',
            },
        ),
        migrations.CreateModel(
            name='DopPoleNaDome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adresa.dom', verbose_name='Дом')),
                ('dop_pole_doma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adresa.doppoledoma', verbose_name='Доп поле дома')),
            ],
            options={
                'verbose_name': 'Доп поле для домов',
                'verbose_name_plural': 'Доп поля для домов',
            },
        ),
    ]
