# Generated by Django 4.2 on 2023-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0013_doppolenadome_znachenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='flat_cadnum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кдастровый номер'),
        ),
    ]
