# Generated by Django 4.2 on 2023-04-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresa', '0003_dom_vladelez_zdania'),
        ('proekti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoglosovaniePoProektu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_priniatia_reshenia', models.DateField(blank=True, null=True, verbose_name='Дата принятия решения')),
                ('scan_documenta', models.FileField(blank=True, null=True, upload_to='', verbose_name='Скан документа')),
                ('dom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adresa.dom', verbose_name='Дом')),
                ('proekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proekti.proekt', verbose_name='Проект')),
                ('tip_reshenia_po_proektu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proekti.tipresheniapoproektu')),
            ],
            options={
                'verbose_name': 'Согласование по проекту',
                'verbose_name_plural': 'Решение по проекту',
            },
        ),
        migrations.CreateModel(
            name='StatusSoglasovania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус согласования',
                'verbose_name_plural': 'Статусы согласования',
            },
        ),
        migrations.AlterField(
            model_name='resheniepoproektu',
            name='status_ispolnenia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proekti.statusispolnenia', verbose_name='Статус исполения решения'),
        ),
        migrations.CreateModel(
            name='SoglosovaniePoProektuDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soglosovanie_po_proektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proekti.soglosovaniepoproektu', verbose_name='Согласование')),
                ('soglosushi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proekti.uchastnikrabochaiagruppa', verbose_name='Согласующий')),
                ('status_soglasovania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proekti.statussoglasovania', verbose_name='Статус согласования')),
            ],
            options={
                'verbose_name': 'Согласование по проекту детализация',
                'verbose_name_plural': 'Согласование по проекту детализация',
            },
        ),
    ]
