# Generated by Django 4.2 on 2023-04-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proekti', '0004_doppolenaproekte_znachenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doppolenaproekte',
            name='dop_pole_proekta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proekti.doppoleproekta', verbose_name='Доп поле проекта'),
        ),
    ]
