# Generated by Django 4.2 on 2023-04-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proekti', '0007_remove_resheniepoproektu_otvestveni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resheniepoproektu',
            name='data_ispolnenia_po_resheniyu',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата для исполненения решения(календарь)'),
        ),
    ]
