# Generated by Django 4.2 on 2023-04-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proekti', '0008_alter_resheniepoproektu_data_ispolnenia_po_resheniyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='resheniepoproektu',
            name='nomer_protokola',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер протокола'),
        ),
        migrations.AlterField(
            model_name='resheniepoproektu',
            name='data_ispolnenia_po_resheniyu',
            field=models.DateField(blank=True, null=True, verbose_name='Дата для исполненения решения'),
        ),
    ]
