# Generated by Django 4.2 on 2023-04-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipVladelza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип владельца',
                'verbose_name_plural': 'Тип владельца',
            },
        ),
        migrations.CreateModel(
            name='VladelezZdania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название или ФИО')),
                ('primechanie', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('telefon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('tip_vladelza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vladelzi_zdani.tipvladelza', verbose_name='Тип владельца')),
            ],
            options={
                'verbose_name': 'Владелец здания',
                'verbose_name_plural': 'Владелецы здания',
            },
        ),
    ]
