# Generated by Django 4.2 on 2023-04-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vladelzi_zdani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zastroyshik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
    ]
